name: KmmBridge integration test

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"
      
      # TODO we'll want to be able to specify branch/commit/tag probably. For PoC, just use main.
      - name: "Checkout plugin"
        uses: actions/checkout@v3
        with:
          repository: touchlab/kmmbridge
          path: build/kmmbridge

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        with:
          min-wrapper-count: 2 # Validating both the local wrapper and the one in the cloned plugin

      # Copied from KMMBridgeGithubWorkflow
      - name: Apply SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.PODSPEC_SSH_KEY }}

      # Copied from KMMBridgeGithubWorkflow
      - uses: extractions/netrc@v1
        with:
          machine: api.github.com
          username: "cirunner"
          password: ${{ secrets.GITHUB_TOKEN }}

      # Copied from KMMBridgeGithubWorkflow
      - name: Cache build tooling
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Local publish plugin
        run: |
          cd build/kmmbridge
          ./gradlew publishToMavenLocal -PRELEASE_SIGNING_ENABLED=false -PVERSION_NAME=999

      # Copied from KMMBridgeGithubWorkflow
      - name: Publish shared
        run: ./gradlew kmmBridgePublish -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=${{ github.repository }} ${{ secrets.gradle_params }} --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:MaxPermSize=2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"

      # TODO need to verify that we're building against the newly published version
      - name: Build SPM Sample
        run: |
          cd ios-spm
          swift package reset
          xcodebuild -configuration Debug -scheme KmmBridgeIntegrationTestSpm -sdk iphonesimulator 

      - name: Build Cocoapods Sample
        run: |
          cd ios-cocoapods
          pod install
          xcodebuild -workspace KmmBridgeIntegrationTestCocoapods.xcworkspace -configuration Debug -scheme KmmBridgeIntegrationTestCocoapods -sdk iphonesimulator 
        
        
        
        
        
